apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: secrets-not-from-env-vars-cve-2024-3177
  annotations:
    policies.kyverno.io/title: Prevent CVE-2024-3177
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: low
    policies.kyverno.io/subject: Pod, Secret, envFrom
    kyverno.io/kyverno-version: 1.11.0
    policies.kyverno.io/description: >-
      Secrets used as environment variables containing sensitive information may, if not carefully controlled,
      be printed in log output which could be visible to unauthorized people and captured in forwarding
      applications. This policy specifically blocks CVE-2024-3177
spec:
  validationFailureAction: Audit
  background: true
  rules:
  - name: secrets-not-from-envfrom-cve-2024-3177
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "Secrets must not come from envFrom statements. CVE-2024-3177"
      pattern:
        metadata:
          annotations:
            kubernetes.io/enforce-mountable-secrets: "true"
        spec:
          =(ephemeralContainers):
            - name: "*"
              =(envFrom):
              - X(secretRef): "null"
          =(initContainers):
            - name: "*"
              =(envFrom):
              - X(secretRef): "null"
          containers:
            - name: "*"
              =(envFrom):
              - X(secretRef): "null"
